"""Carrot Quest API models."""

from .apps import (
    ActiveUsersResponse,
    AppChannelsResponse,
    AppConversationsResponse,
    AppUsersData,
    AppUsersResponse,
    UserListItem,
)
from .conversations import (
    ConversationAssignResponse,
    ConversationReplyResponse,
    ConversationTagResponse,
    EmptyResponse,
    GetConversationPartsResponse,
    GetConversationResponse,
)
from .objects import (
    Admin,
    Attachment,
    Channel,
    Conversation,
    ConversationAction,
    ConversationPart,
    EmailStatus,
    Event,
    EventType,
    MessageSender,
    Note,
    PresenceDetails,
    ResponseMeta,
    Segment,
    User,
    UserEventInfo,
    UserTag,
)
from .users import (
    GetUserConversationsResponse,
    GetUserEventsResponse,
    GetUserResponse,
    RecordUserEventResponse,
    SendMessageResponse,
    SetPresenceResponse,
    SetUserPropsResponse,
    StartConversationResponse,
    UnsubscribeEmailResponse,
)

__all__ = [
    # Apps models
    "ActiveUsersResponse",
    "AppChannelsResponse",
    "AppConversationsResponse",
    "AppUsersData",
    "AppUsersResponse",
    "UserListItem",
    # Object models
    "Admin",
    "Attachment",
    "Channel",
    "Conversation",
    "ConversationAction",
    "ConversationPart",
    "EmailStatus",
    "Event",
    "EventType",
    "MessageSender",
    "Note",
    "PresenceDetails",
    "ResponseMeta",
    "Segment",
    "User",
    "UserEventInfo",
    "UserTag",
    # Conversations models
    "ConversationAssignResponse",
    "ConversationReplyResponse",
    "ConversationTagResponse",
    "EmptyResponse",
    "GetConversationPartsResponse",
    "GetConversationResponse",
    # Users models
    "GetUserConversationsResponse",
    "GetUserEventsResponse",
    "GetUserResponse",
    "RecordUserEventResponse",
    "SendMessageResponse",
    "SetPresenceResponse",
    "SetUserPropsResponse",
    "StartConversationResponse",
    "UnsubscribeEmailResponse",
]
